version: '3.7'
services:
  rest:
    container_name: rest
    build: ./rest.bitcoin.com
    depends_on:
      - insight
    networks:
      - bitcoin
    ports:
      - "3000:3000"
  insight:
    image: christroutner/insight-bch-0.20.4
    command: ./start-app.sh
    networks:
      - bitcoin
    volumes:
      - ./insight-api/start-app.sh:/home/insight/start-app.sh
      - ./blockchain-data:/home/insight/blockchain-data
      - ./insight-api/bitcoin.conf:/home/insight/.bitcoin/bitcoin.conf
      - ./insight-api/bitcore-node.json:/home/insight/.bitcore/bitcore-node.json
 
networks:
    bitcoin:
        name: bitcoin
